### ISSUE TITLE
Is this repo for both SIP and WebRTC ?

### ISSUE THREAD

**Issue by CCMeta** [sipsorcery-org/SIPSorceryMedia.Abstractions#1]
I do not know anything about SIP things, Only work on WebRTC.

Clearly RTC need both Video and Audio medias to be worked on. 

Is any Video Media On SIP Already?  

Or is this necessary to develop on this repo from now ?

A guy was take an issue for codecs, But Seems He Only used SIP, No any RTC staff things. 

Could you tell me some plans of this repo? Such as ffmpeg or else.  
If you No Plan to take RTC staff. PLZ tell me.
Which me should do ? Wait or Write?

**Comment by sipsorcery** [comment]
The interfaces in this library work almost identically no matter if your application is for SIP or WebRTC.

> Or is this necessary to develop on this repo from now ?

This repo will only ever be for an interface only, it's not intended to add any implementations to it. Currently the two separate libraries from me that implement this interface in some form are:

 - [SIPSorceryMedia.Windows](https://github.com/sipsorcery/SIPSorceryMedia.Windows). 

 - [SIPSorceryMedia.FFmpeg](https://github.com/sipsorcery/SIPSorceryMedia.FFmpeg).

The Windows library is in a working states and allows audio and video sessions to be established with both SIP and WebRTC. Almost all the [examples](https://github.com/sipsorcery/sipsorcery/tree/master/examples) are now using the [SIPSorceryMedia.Windows](https://github.com/sipsorcery/SIPSorceryMedia.Windows) library, oth SIP and WebRTC.

The FFmpeg library is not yet ready and there are no examples for it. I plan on working on it over the next few weeks. If all goes well it should allow full audio, video and codec support on any platform that can install the FFmpeg libraries.

If the platform you're developing on, which I believe is Xamarin and Android in your case, isn't Windows or able to host FFmpeg libraries then the idea is you would need to do your own implementation of the interfaces in this library. You could start with just a single media end point such as the [AudioSource](https://github.com/sipsorcery/SIPSorceryMedia.Abstractions/blob/34989278169906b12fa5c0a0496b19b5f9e02725/src/V1/MediaEndPoints.cs#L75) or [AudioSink](https://github.com/sipsorcery/SIPSorceryMedia.Abstractions/blob/34989278169906b12fa5c0a0496b19b5f9e02725/src/V1/MediaEndPoints.cs#L98). If you're able to do that then you'll be able to easily wire up the audio functionality to the WebRTC stack in the main sipsorcery library.

**Comment by CCMeta** [comment]
Hello.
May I ask U where is my dear `opus/48000` in this repo? 
Will U add her someday later?
tkx a lot

**Comment by sipsorcery** [comment]
There is no OPUS wrapper unfortunately. I'm still bogged down on VP8 and I don't know if/when I'll get onto doing anything with OPUS.
